//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kanban_API
{
    using Models;
    using System;
    using System.Collections.Generic;
    using AutoMapper;

    public partial class Card
    {
        public Card()
        {

        }

        public Card(CardModel card)
        {
            this.Update(card);
            card.CreatDate = DateTime.Now;
        }
        public int CardId { get; set; }
        public int ListID { get; set; }
        public System.DateTime CreatDate { get; set; }
        public string Text { get; set; }

        public virtual List List { get; set; }

        public void Update(CardModel model)
        {
            CardId = model.CardId;
            ListID = model.ListID;
            CreatDate = model.CreatDate;
            Text = model.Text;
        }

    }
}
